"use strict";
exports.__esModule = true;
var express_1 = require("express");
var user_controller_1 = require("../controllers/user.controller");
var auth_middleware_1 = require("../middlewares/auth.middleware");
var router = (0, express_1.Router)();
router.post('/register', user_controller_1.userRegister);
router.post('/login', user_controller_1.userLogin);
router.post('/upload', auth_middleware_1.authMiddleware['user'], user_controller_1.uploadAssignment);
router.post('/admins', auth_middleware_1.authMiddleware['user'], user_controller_1.getAdmins);
router.post('/me', auth_middleware_1.authMiddleware['user'], user_controller_1.getCurrentUser);
router.post('/update', auth_middleware_1.authMiddleware['user'], user_controller_1.updateUser);
router.post('/delete', auth_middleware_1.authMiddleware['user'], user_controller_1.deleteUser);
exports["default"] = router;
