name: Auto Commit Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write  

jobs:
  auto-commit:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Changes Script
        run: |
          echo "This is a change made by the pipeline on $(date)" >> README.md

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Changes
        run: |
          git pull --rebase origin main
          git add .
          git commit -m "Automated commit on $(date)" || echo "No changes to commit"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
