name: Auto Commit Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Make Changes
        run: |
          echo "Automated change made by pipeline on $(date)" >> README.md

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Automated commit on $(date)" || echo "No changes to commit"

      - name: Stash and Pull Changes
        run: |
          git stash
          git pull --rebase origin main
          git stash pop || echo "No stash to apply"

      - name: Push Changes
        run: git push origin main
