name: Auto Commit Workflow

on:
  push:
    branches:
      - main  

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Make changes or run a script
      - name: Run Changes Script
        run: |
          echo "This is a change made by the pipeline on $(date)" >> README.md

      # Step 3: Configure Git with a generic user
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 4: Commit and push changes if there are any
      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Automated commit on $(date)" || echo "No changes to commit"
          git push origin main